### PR TITLE
Feature/issue 38

### PR DESCRIPTION
**Pull request by malakai97**
Uploading this now because I wanted some feedback on the strategy within the spec (https://github.com/hathitrust/ht_sip_validator/blob/86ef223c103f6649143504d47179bb1dbaedbe1c/spec/validation/meta_yml/date_format_spec.rb)

### CODE REVIEW

**Comment by aelkiss** [comment]
I think testing the messages to the level of detail that the error generation is duplicated between the validator and the specs is probably not useful. If there are multiple kinds of error messages that the validator can return, then check enough to differentiate between them - otherwise just test that the features of the error you care about make it through (e.g. vaguely date related and that it shows the user where the offending date was). Testing that the interface actually works and that messages returned from validators aren't changed in unexpected ways probably only needs to be tested once.

**Comment by malakai97** [comment]
Agreed.  The presence of the duplication here is telling me that some of the properties of a message should be extracted into some data file.  Then the test can still specify the message it expects in detail, without including those details in the test.

**Comment by malakai97** [comment]
[This](https://github.com/hathitrust/ht_sip_validator/blob/86ef223c103f6649143504d47179bb1dbaedbe1c/spec/validation/meta_yml/date_format_spec.rb) is what the spec looks like after moving the message format "specification" into a yaml file (config/messages.yml), and providing a helper.

**Comment by aelkiss** [comment]
Is the plan that the actual validator would use the messages from config/messages.yml as well? Are you planning to add the validator on this PR as well, or do you want to merge this one and work on the validator later?

**Comment by malakai97** [comment]
> Is the plan that the actual validator would use the messages from config/messages.yml as well?

To the extent possible (looking at you, extra fields), yes.

> Are you planning to add the validator on this PR as well, or do you want to merge this one and work on the validator later?

Most likely I'll add the validator to this one as well.  Assuming we like this strategy, we can begin using it going forward without having to port the "old" validators over.

**Comment by aelkiss** [comment]
OK, sounds good. I'll keep an eye out for new commits.

**Comment by malakai97** [comment]
Closing this PR and branch as its fallen far enough behind that a merge is a big pain (indentation AND rubocop).  I have the logic moved over to another branch locally, and will submit a PR when that's ready.

**Pull request closed without merging**
